import Head from "next/head";
import Image from "next/image";
import { ReactElement } from "react";

export default function Home(): ReactElement {
  return (
    <div>
      <Head>
        <title>Windows clone os</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Hi how are you?</h1>
    </div>
  );
}
